# Standalone mode.
is_alone: true

robot_name: 'dude'
# This goes to making up part of the platform_info triple.
robot_type: 'turtlebot'

# This is very non-portable, if doing from source directories, use $(find..) in the launchers instead
# app_from_source_directory: '/home/jihoonl/ros/groovy/turtlebot/turtlebot_apps/turtlebot_core_apps'

app_store_url: []

white_list: ["concert_master"]
black_list: ["pirate_master"]

remote_name: "gateway1"
