# Standalone mode.
is_alone: true

robot_name: 'chopin'
robot_type: 'turtlebot'

# This is bad.
app_from_source_directory: '/home/jihoonl/ros/groovy/turtlebot/turtlebot_apps/turtlebot_core_apps'

app_store_url: []

white_list: ["concert_master"]
black_list: ["pirate_master"]

remote_name: "gateway1"
